basic_settings:
  site_title: Esther Coaching
  favicon_image: /images/favicon.ico
  og_image: /images/screenshot.png
  logo_image: /images/ev.png

footer_settings:
  footer_tagline: Currently located in Chiang Mai, Thailand

# menu_settings:
#   menu_items:
#     - title: 'About'
#       url: '/about'
#     - title: 'Consulting'
#       url: '/services'
#     - title: 'Blog'
#       url: '/blog/'
#     - title: 'Contact'
#       url: '/contact'

contact_settings:
  email: busababruns@gmail.com
  email_subject: Message via Esther Coaching Website
  send_button_text: Send Message
  phone: ''
  scheduling_link: '#contact'
  mailchimpembed: ''

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  youtube_url: ''
  pinterest_url: ''
  linkedin_url: ''

colors:
  primary_color: '#ff66cc'
  secondary_color: '#00BFB3'
  tertiery_color: '#CCFF66'
  light_color: '#91E3DE'
  dark_color: '#180010'
